hypha-dao/dho-web-client

src/pages/payouts/components/payout-proposal-view.vue

Payout url

---

src/store/profiles/actions.js

Add limit attribute to override the default

---

src/store/accounts/actions.js
src/store/profiles/actions.js

Keep the drafts when login out

Fix the loading of the draft

---

src/components/layout/left-menu.vue
src/components/layout/right-sidebar.vue
src/pages/dashboard/dashboard.vue
src/pages/payouts/components/payout-form.vue
src/pages/proposals/components/draft-proposal-card.vue
src/pages/proposals/components/proposal-card.vue
src/pages/proposals/list/proposals-list.vue
src/store/payouts/actions.js

Fix the publication of a contribution

---

package.json

Release 1.0.34

---

src/pages/multi-sig/multi-sig-list.vue

Actions label

---

src/components/form/period-select.vue
src/pages/assignments/components/assignment-card.vue
src/pages/assignments/components/assignment-form.vue
src/pages/assignments/components/assignment-proposal-view.vue
src/pages/assignments/components/assignment-view.vue
src/pages/profiles/view/wallet-view.vue
src/store/assignments/actions.js

Fix USD and edit assignment

---

package.json
src/pages/assignments/components/assignment-card.vue
src/pages/assignments/list/assignment-list.vue
src/store/assignments/actions.js

Fix claiming issue

---

package.json
src/pages/assignments/components/assignment-card.vue

Fixing claiming button

---

package.json
src/pages/applicants/components/applicant-card.vue
src/pages/applicants/list/applicants-list.vue
src/store/applicants/actions.js
src/store/applicants/getters.js
src/store/applicants/mutations.js
src/store/applicants/state.js

Fix applicants list

---

package.json
src/pages/applicants/components/applicant-card.vue

Fix applicant enroll

---

package.json
src/components/layout/right-menu-notifications.vue
src/store/notifications/mutations.js

Help the support

---

package.json
src/store/assignments/actions.js

Fix general assignments list

---

src/pages/assignments/components/assignment-card.vue
src/pages/assignments/components/assignment-form.vue
src/store/assignments/actions.js

- Update help messages for all assignment options
- Rename Edit to Modify
- Update suspend icon
- Add action for new dynamic commit
- Fix popup-proxy background color on mobile

Add dynamic commitment

---

src/boot/config.js
src/pages/assignments/components/assignment-proposal-card-draft.vue
src/pages/badges/components/badge-assignment-proposal-card-draft.vue

This allows us to test shorter periods on testnet

Remove hardcoded vote duration

---

.gitignore

Changing the gitignore to force workflow to deploy new secrets to test

Adding extra dev/prod env files to ignore

---

src/pages/payouts/components/payout-form.vue

Made SEEDS field readonly #391

---

src/store/assignments/actions.js

Fixed the contract parameters on call to withdraw active assignment.

Fix withdraw assignment

---

src/pages/profiles/components/wallet.vue

Change redeem label to HUSD

---

src/router/routes.js

This will revert the route change that brings down the dho website.
This reverts commit 48ecbe83d51ecbc168ebe8e6729f02bc8ae7c617.

Restore DHO Website

---

src/components/common/progress-percentage.vue
src/components/navigation/alert-message.vue
src/components/navigation/dho-switcher.vue
src/components/navigation/left-navigation.vue
src/components/navigation/navigation-header.vue
src/components/navigation/profile-sidebar.stories.js
src/components/navigation/profile-sidebar.vue
src/components/navigation/quick-actions.vue
src/components/profiles/members-filter.vue
src/components/profiles/profile-card.vue
src/components/profiles/profile-picture.vue
src/components/proposals/proposal-card.vue
src/components/proposals/proposal-filters.vue
src/components/proposals/voting-result.vue
src/layouts/MultiDhoLayout.vue
src/pages/dho/Home.vue
src/pages/dho/Overview.vue
src/pages/members/Members.vue
src/pages/proposals/ActiveProposals.vue
src/pages/proposals/ProposalCreate.vue
src/pages/proposals/ProposalDetail.vue
src/router/routes.js

- Add status message to preview pages
- Update dho home page
- Clean up proposal page preview
- Remove filler data members page

Clean up routing, update breadcrumbs

---

.github/ISSUE_TEMPLATE/Bug.yaml
.github/ISSUE_TEMPLATE/Feature.yaml
.github/ISSUE_TEMPLATE/config.yaml

The YAML templates reside in .github/ISSUE_TEMPLATE

Adding ISSUE_TEMPLATES to allow folks to create nice issues

---

.github/ISSUE_TEMPLATE/Bug.yaml
.github/ISSUE_TEMPLATE/Feature.yaml

Update on issue templates

---

.github/workflows/deploy-dev.yml

Update node version to use in develop staging

Change node-version to 14.x for deploy dev

---

src/components/login/login-view.vue
src/components/login/register-user-view.vue
src/layouts/DhoSelector.vue
src/pages/onboarding/NLogin.vue
src/router/routes.js

Fix login and new user flow

---

src/components/login/register-user-view.vue
src/layouts/DhoSelector.vue
src/pages/dho/Organizational.vue
src/query/dao-archetypes.gql
src/query/main-dho.gql
src/store/dao/index.js

- Add Dho query to get settings
- Added archetypes query and implemented to widget
- Fix number phone and code country sizes

Added Dho query to get settings and archetypes query

---

src/components/organization/archetypes-widget.vue
src/layouts/DhoSelector.vue

commented log

---

src/store/dao/index.js
src/store/treasury/actions.js

- Add getter on store to get tokens symbols
- Modify functionality in treasury action to get amount by token.

Add functionality to get tokens by dao

---

src/pages/dho/Home.vue

- Deleted console log
- Change format to save amoun and symbol in token object
- Addet token symbol on title

Change format for tokens to save the symbol and put in the title

---

src/pages/dho/Home.vue

Fix slint issues for home page

Fix slint issues for home page

---

.env.example
src/boot/config.js
src/components/profiles/wallet.vue
src/store/profiles/actions.js
src/utils/eosio.js

+ Added a nameToUint64  method to utils
+ Fetching dHypha amount from the smart contract on getTokensAmounts method
+ Added dHypha to wallet component

Added dHypha to wallet component

---

src/pages/dho/Organizational.vue

Remove console logs

---

.github/workflows/deploy-dev.yml

- Changed dao contract for new multitenant contract in dev env for DEV

Change Dao contract for the new multitenant contract for dev deploy env

---

src/components/common/widget.vue
src/pages/profiles/Profile.vue
src/store/ballots/actions.js

- Fix console log eslint disabld
- Fix padding in widget component

Add eslint ignore for error consol and fix padding in widget

---

src/pages/Error404Page.vue
src/router/routes.js

https://github.com/hypha-dao/dho-web-client/issues/635

Added 404 Error Page - wrong URL (#635)

---

src/layouts/MultiDhoLayout.vue

Fixed a bug where the profile info was not being shown on the sidebar

Added account watcher to MultiDhoLayout

---

src/apollo/apollo-client-hooks.js
src/components/common/empty-widget-label.vue
src/components/navigation/guest-menu.vue
src/components/navigation/non-member-menu.vue
src/components/profiles/member-banner.vue
src/components/proposals/proposal-banner.vue
src/components/proposals/voting.vue
src/layouts/DhoSelector.vue
src/layouts/MultiDhoLayout.vue
src/pages/dho/Members.vue
src/pages/proposals/ActiveProposals.vue
src/query/account/dao-applicant.gql
src/query/account/dao-member.gql
src/store/accounts/actions.js
src/store/dao/index.js
src/store/members/actions.js

+ Disabled some buttons for guests
+ Added membership apply buttons 
#679 #680

Added guest access controll

---

src/layouts/MultiDhoLayout.vue
src/pages/support/Support.vue
src/router/routes.js

https://github.com/hypha-dao/dho-web-client/issues/645

Help / Transactions Page (#645)

---

src/components/profiles/organizations.stories.js
src/components/profiles/organizations.vue
src/pages/profiles/Profile.vue
src/query/profile/profile-dhos.gql
src/utils/slugify.js

https://github.com/hypha-dao/dho-web-client/issues/268
@leonieherma1 Please note there should be a new ticket for reading the logo of DHO from the backend as that is not ready on the backend part, so there is the placeholder currently. Also what happens when the person is the member of many DHO's ? Do we show all or do we have pagination? The current design is not covering that.

DHO My Profile - My Organizations Widget (#268)

---

src/components/profiles/wallet-base.vue
src/components/profiles/wallet.vue
src/store/payments/actions.js

* Neet to be tested in production as soon as deployed

Added buy hypha button and transaction

---

src/components/profiles/organizations.vue

https://github.com/hypha-dao/dho-web-client/issues/268#issuecomment-1050265246

Adding visual corrections for the organisations widget (#268)

---

src/components/navigation/dho-btn.vue
src/components/navigation/left-navigation.vue
src/layouts/MultiDhoLayout.vue

- Fixed https://github.com/hypha-dao/dho-web-client/issues/768
- Fixed https://github.com/hypha-dao/dho-web-client/issues/769
- Fixed small issues

Fixixed isses regarding pk login and dao selector

---

src/components/proposals/proposal-card.vue
src/components/proposals/proposal-suspended.vue
src/components/proposals/voter-list.vue
src/components/proposals/voting.vue
src/pages/dho/Explore.vue
src/pages/proposals/ProposalDetail.vue
src/store/proposals/index.js

- Add functionality for activate button on proposals
- Add functionality for archive button on proposals
- Create action for active and archive proposal
- Add the new pagination for votes
- Fix the pagination and filter for exploring page
- Add the new component for suspending the proposal
- Change the color for the suspension tag
- Add validation for different states

Feat and fixes

---

src/pages/dho/Explore.vue

- Change value when dao name is null
- Return data when restarting the list

Fix the first pagination

---

src/components/proposals/voting.vue

- Fix when user click to vote
- Refactor organization with voting actions

Fix when user click to vote and better organization for vote actions

---

src/components/login/register-user-view.vue

- Removed upload image label from registration user

Removed upload image in finish registration user

---

src/pages/proposals/create/StepCompensation.vue

Add the to fixed method

---

src/pages/proposals/ProposalCreate.vue

- Fixed behavior when a proposal is created succesffully (Skip leave page confirmation)

Fix lave page when a proposal is created sseuccessfully

---

src/components/proposals/voting.vue

- Modify a button for change the vote #825 
- Add a tooltip for the user

Modify the button to change the vote

---

src/pages/proposals/ActiveProposals.vue

- Remove the functionality to order the voting list by user voting

Comment the function to order by user voting

---

src/pages/proposals/ProposalDetail.vue

- Remove unnecessary action, the correct action is ballot > supply

Remove unnecessary action

---

src/components/common/base-banner.vue
src/components/login/register-user-view.vue
src/components/navigation/left-navigation.vue
src/components/navigation/profile-sidebar.vue
src/components/navigation/quick-links.vue
src/css/quasar.variables.styl
src/layouts/MultiDhoLayout.vue
src/pages/dho/Home.vue

+Updated screen breakpoints
+Updated styles to support smaller screens
TODO:
*Need to fix some minor visual errors
*Need to fix register screen on smaller screens

Adding support for 1366x768 resolution 

---

src/components/form/custom-period-input.vue
src/pages/dho/Configuration.vue

https://github.com/hypha-dao/dho-web-client/issues/565

Disable editing of the config if user is not admin

---

src/layouts/EmptyLayout.vue
src/pages/dho/Explore.vue
src/router/routes.js

Root page overrited and sticky position for explorer page

---

src/components/navigation/dho-info.vue

- Add the format on duration times for dev page

Format duration

---

src/components/common/chips.vue
src/components/profiles/profile-picture.vue
src/components/proposals/proposal-view.vue
src/components/proposals/voter-list.vue
src/pages/proposals/ProposalDetail.vue
src/utils/eosio.js

- Fix the percentage on the voter list
- Add limit with for name on voter list
- Add new prop for chip component
- Fix console error for proposal

Voter list

---

src/components/navigation/dho-info.vue
src/pages/proposals/ProposalDetail.vue

- Modify the format for the time duration

Modify the time format

---

src/pages/onboarding/create.vue

Remove console log

---

src/components/profiles/proposal-item.vue
src/components/proposals/proposal-card.vue
src/components/proposals/voting.vue

Change the configuration for the colo bar on components with the voting percentage

Add the config color for the voting bar

---

src/components/assignments/assignment-claim-extend.vue
src/components/assignments/assignment-header.vue
src/components/profiles/proposal-item.vue
src/components/proposals/voting.vue
src/pages/proposals/create/config.json

- Disable apply for assignments
- Disable claim for assignments with deferred lass than 100%
- Disable creation for contributions and assignments

Temporal changesnges to disable some features

---

src/components/login/register-user-view.vue

closes https://github.com/hypha-dao/dho-web-client/issues/873

Add check phone number link

---

src/pages/search/Results.vue

Removed Circle from Widget

---

src/components/dashboard/metric-link.vue
src/pages/dho/Organizational.vue

- Fixed redirections for oror kpi on organizational pages

Fixed redirections for oror kpi on organizational pages

---

src/elasticSearch/elastic-search.js
src/pages/search/Results.vue
src/pages/search/components/result.vue

Search Result supports only Assignments

---

.github/workflows/deploy-dev.yml

- Implemented vars for IPFS on dev

UpdatUpdated dev env vars for github

---

src/pages/dho/Configuration.vue
src/pages/proposals/create/config.json

- Implemented ipfs components on configuration page

Addindded ipfs components to configuration page

---

src/pages/proposals/create/StepCompensation.vue
src/pages/proposals/create/StepDateDuration.vue

- Fix validation to create contribution in custom fields
- Added validations to calculate and paint periods selected from drafts

Fix duration params from draft

---

src/pages/profiles/profile-creation.vue

Closes https://github.com/hypha-dao/dho-web-client/issues/955

Add rich text editor for the bio field

---

src/components/common/button-radio.vue
src/pages/proposals/create/StepProposalType.vue

- Add a new prop to set a min-height on button radio component

Fix heigth in button radio for create page

---

src/store/profiles/actions.js

-Fix VOICE token fetch
-Added dHypha for hypha dao

Fixed wallet tokens

---

src/pages/proposals/ProposalDetail.vue

- Fix the creator on Assign badge and assignments

Fix the creator on assignbadge and assignments

---

src/pages/proposals/ProposalDetail.vue

- Add the commit method for the proposal detail

Add the commit value for assignments

---

src/components/profiles/proposal-item.vue
src/pages/proposals/ProposalDetail.vue

- Add error notification for claiming an active proposal

Add a error notification

---

src/components/proposals/proposal-dynamic-popup.vue
src/components/proposals/proposal-view.vue
src/pages/proposals/ProposalDetail.vue
src/query/proposals/dao-proposal-detail.gql
src/query/proposals/dao-proposals-active-vote.gql
src/store/assignments/actions.js

Added dynamic deferred and commit pop up

---

src/pages/dho/Home.vue
src/pages/dho/Organizational.vue

- Replace the KPIs on the home page

Change kpis

---

src/components/profiles/proposal-item.vue
src/query/profile/profile-contributions.gql

- Modify the page to get the correct value for the compensation
- Modify the query to get the correct field

Change the compensation value

---

src/components/navigation/profile-sidebar.vue
src/components/navigation/quick-links.vue
src/components/profiles/about.vue
src/components/profiles/profile-card.vue
src/pages/profiles/edit/profile-edit.vue
src/store/profiles/actions.js
src/utils/turndown.js

closes https://github.com/hypha-dao/dho-web-client/issues/1063
closes https://github.com/hypha-dao/dho-web-client/issues/985
closes https://github.com/hypha-dao/dho-web-client/issues/707

Various dashboard fixes

---

src/pages/proposals/ProposalDetail.vue

- Uncomment the validation for is custom for the deferred amount

Fix the validation for the deferred amount if is custom

---

src/pages/search/Results.vue

- Fix the values when user select the voting status #1010

Fix the value for voting status

---

src/router/index.js
src/router/routes.js

Redirect tempororally root to hypha explorer page

Redirect tempororally root to hypha explorer page

---

src/pages/proposals/ProposalList.vue

- Add the filter for badge assignments #1082

Add the filter for badge assignments

---

src/components/login/welcome-view.vue
src/components/navigation/dho-card.vue
src/pages/dho/Explore.vue
src/pages/dho/Home.vue
src/query/dao/dao-list-asc.gql
src/query/dao/dao-list-recent.gql
src/store/dao/getters.js

Implemented title dao for explorer and selected dao

Implemented title dao for explorer and selected dao

---

src/App.vue
src/components/ipfs/ipfs-image-viewer.vue
src/components/login/header-view.vue
src/components/navigation/dho-btn.vue
src/components/navigation/dho-card.vue
src/components/navigation/left-navigation.vue
src/index.template.html
src/layouts/DhoSelector.vue
src/layouts/MultiDhoLayout.vue
src/pages/dho/Explore.vue
src/pages/onboarding/NLogin.vue
src/query/dao/dao-list-recent.gql
src/query/profile/profile-dhos.gql
src/router/index.js
src/store/dao/getters.js

Split all changes for logo icons

---

src/pages/dho/Members.vue

- Fix the order for the member's page

Fix the order on members page

---

src/pages/dho/Organizational.vue
src/pages/treasury/treasury.vue

- Remove the seeds token on treasury and organizational

Remove seeds

---

src/pages/proposals/create/OptionsArchetypes.vue
src/pages/proposals/create/StepDateDuration.vue

- Fix the flips after selecting a card on role
- Fix the error when the user resets the selection and select another date
- Add a new variable to manage the reset periods to not load the draft periods
- Remove a validation proposal is a draft

Fix the filter

---

src/pages/proposals/ProposalDetail.vue

- Remove active label for badge and role
- #1087

Remove active label for badge and role

---

src/components/proposals/proposal-list.vue
src/pages/proposals/ProposalList.vue

- Fix the error when loading the staging proposal 
- Return an object for the compensation method to remove the console error
- Add the filter by type for staging proposal
- [#1082](https://github.com/hypha-dao/dho-web-client/issues/1082)

Add filter for staging proposal and fix errors on proposals

---

src/pages/proposals/ProposalDetail.vue

- Add the role archetype title for the edit type

Modify the validation if is edit type

---

src/query/proposals/dao-proposals-active-vote.gql

- Fix the query for proposal list

Fix query for proposal list

---

src/components/navigation/bottom-navigation.vue
src/components/navigation/left-navigation.vue
src/pages/proposals/ProposalCreate.vue

closes https://github.com/hypha-dao/dho-web-client/issues/1104

Change organizaton icon in the sidebar navigation

---

src/pages/proposals/ProposalList.vue

closes https://github.com/hypha-dao/dho-web-client/issues/1127

Add toggle to show/hide staged proposals

---

src/components/profiles/proposal-item.vue
src/pages/proposals/create/config.json

- Disable contribution creation
- Disable claim for less 100 comitment

Disbable HUSD

---

src/App.vue
src/layouts/MultiDhoLayout.vue
src/pages/dho/Explore.vue
src/pages/dho/Home.vue
src/pages/dho/Members.vue
src/pages/dho/MinExplore.vue
src/pages/dho/Treasury.vue
src/pages/profiles/Profile.vue
src/pages/proposals/ProposalList.vue
src/pages/support/Support.vue
src/router/index.js
src/router/routes.js

closes https://github.com/hypha-dao/dho-web-client/issues/1151

Add meta title to the routes

---

src/pages/dho/Finflow.vue
src/query/assignments/dao-approved-assignments.gql
src/router/routes.js

#1156 
Notes:
- Added a new route /finflow where you can see the finance dashboard

Added finflow dashboard

---

src/components/profiles/proposal-item.vue
src/pages/proposals/create/config.json

Reverts hypha-dao/dho-web-client#1159

Revert "Disbable HUSD"

---

src/pages/dho/Explore.vue

- Change the label on the type of sort
- Add a new type of sort
- #1170

Add a new option to sort

---

src/pages/dho/Explore.vue

- Change the labels for the selector sort
- Add the descending by default

Change the labels and the default

---

src/pages/dho/Finflow.vue

- Fixed finance table ordering method
- Added CSV export to table
Notes:
You can test going to /finflow route

Added finance table export

---

src/components/proposals/proposal-view.vue

- Fix the tokens amount on assigments

Fix the values for one period and cycles

---

src/query/proposals/dao-proposal-detail.gql
src/query/proposals/dao-proposals-stage.gql

- Replace the old field with the new badge

Change the field for cycles

---

src/pages/proposals/create/StepCompensation.vue

- Add a new computed to verify if the proposal is an assignment
- Add a new input for the assignment tokens

Show differents input if the proposal is assignment

---

src/components/profiles/wallet-adresses.vue
src/pages/profiles/Wallet.vue

closes https://github.com/hypha-dao/dho-web-client/issues/1232
closes https://github.com/hypha-dao/dho-web-client/issues/1231

Wallet page bug fixes

---

package.json
src/boot/ual.js
yarn.lock

- Removed ual-seeds-wallet
- Added lastest ual-seeds (1.1.0)

Update ual seeds package

---

src/components/profiles/profile-picture.vue
src/components/proposals/proposal-card.vue

Task: #1141 
- Showing real name on proposal list item (Active proposals page)

Showing proposal item real user name

---

src/components/proposals/comment-item.vue
src/components/proposals/comments-widget.vue
src/pages/proposals/ProposalDetail.vue

closes https://github.com/hypha-dao/dho-web-client/issues/1236

Proposal comments bug fixes

---

src/components/navigation/quick-links.vue

Task: #1224 
- Fixed right sidebar button dancing.
- (Couldn't reproduce anymore, but need more testing)

Fix right sidebar button dancing

---

src/layouts/MultiDhoLayout.vue

Task: #1114 
- Fixed left sidebar disappearing when resizing fast.

Fix left sidebar disapear on resize

---

src/components/proposals/proposal-card.vue

The votingExpired prop where causing console errors because it was undefined.

Removed undefined votingExpired prop causing errors

---

src/components/navigation/dho-card.vue

Task: #1186 
- Updated DAO card styling (DAO Explorer page)

Updated dho card styles

---

src/components/common/token-value.vue
src/components/proposals/proposal-card-chips.vue
src/mixins/format.js

- Changed number formatting on proposal detail
- Changed number formatting on walllet
- Removed role assignment compensation chip tooltip

Changed number formatting on wallet and proposal detail

---

src/pages/proposals/ProposalDetail.vue

After creating a proposal (role assignment) the commitment level no longer shows NaN on commitment level

ProposalView NaN fix

---

src/pages/proposals/ProposalCreate.vue
src/pages/proposals/create/OptionsArchetypes.vue
src/pages/proposals/create/OptionsBadges.vue

Now the current badge/role is displayed in the header.

Proposal Creation wizard headers updated

---

src/query/periods/dao-periods-range.gql
src/utils/proposal-parsing.js

Task: #1296 
- Updated periods query

Updated periods query

---

src/components/ipfs/ipfs-image-viewer.vue
src/pages/dho/Explore.vue

Task: #1331 
This goes to master because is a priority fix

Fixed explorer filter

---

package.json
public/service-worker.js

This PR adds a self-destructing service worker to fix an infinite loading screen bug due to previous worker caching

Add self-destroying service worker

---

src/components/proposals/proposal-card.vue
src/pages/proposals/ProposalList.vue
src/query/proposals/dao-proposals-active-vote.gql
src/query/proposals/dao-proposals-stage.gql

Added comment counter on proposal cards

---

src/pages/profiles/Wallet.vue

https://github.com/hypha-dao/dho-web-client/issues/1162

Filter payments by dao id

---

src/pages/proposals/create/StepDescription.vue

Paste on description field now working.

Creation Wizard paste fixed

---

src/layouts/DhoSelector.vue

Added mobile in progress alert

---

src/components/login/register-user-view.vue

Registration scrollbar fixed

---

src/mixins/validation.js

accountFormat error message updated

updated error feedback

---

src/components/dao/settings-communication.vue
src/pages/dho/Configuration.vue
src/store/dao/actions.js

This PR fixed ability for DAO admins to save settings due to alert update action order bug.
closes https://github.com/hypha-dao/dho-web-client/issues/1470
closes https://github.com/hypha-dao/dho-web-client/issues/1474
closes https://github.com/hypha-dao/dho-web-client/issues/1446

Configuration page fixes and improvements

---

src/components/dao/settings-communication.vue
src/components/navigation/profile-sidebar.vue
src/components/navigation/sidebar-news.vue
src/layouts/MultiDhoLayout.vue
src/pages/dho/Configuration.vue
src/query/dao-active.gql
src/query/dao-alerts.gql
src/query/dho-alerts.gql
src/store/dao/actions.js
src/store/dao/getters.js
src/store/dao/mutations.js
src/store/dao/state.js
src/store/layout/actions.js

This PR adds the Announcements widget to the configuration page and refactors the alerts.
closes https://github.com/hypha-dao/dho-web-client/issues/1474

feat (configuration page): announcements widget

---

.github/workflows/commitlint.yml
.husky/commit-msg
commitlint.config.js
package.json
yarn.lock

build: add conventional commit

---

.github/workflows/release-please.yml

closes https://github.com/hypha-dao/dho-web-client/issues/1389
| --- | --- |

ci: add automate release 

---

src/components/profiles/proposal-item.vue

fix: revert to claim all with multiple transaction

---

src/components/dao/settings-communication.vue
src/components/dao/settings-design.vue

closes https://github.com/hypha-dao/dho-web-client/issues/1525
closes https://github.com/hypha-dao/dho-web-client/issues/1527

fix(configuration page): remove pattern slip and disable announcement edit for non admins 

---

src/store/dao/mutations.js

Temporarily disabled cash claims for hypha

feat: disabled cash claims for hypha

---

src/pages/search/Results.vue

Filter: Make Document Type filter consistent #1415
- Fixed filter on the search page, added missing filter types

fix: fixed filter on the search page, added missing filter types (#1415)

---

CHANGELOG.md

This PR is fixing wrong changelog notes generated by relase-please

fix(changelog): change relase notes for 2.10

---

src/pages/proposals/create/StepDescription.vue
src/query/proposals/dao-proposal-detail.gql

fix: badge proposal details and formatting issues

---

src/pages/proposals/ProposalDetail.vue
src/pages/proposals/ProposalList.vue

Add "delete button" to staging proposals #1520
- "Delete proposal" button to staging proposals has been added

feat: added "Delete proposal" button to staging proposals (#1520)

---

src/pages/search/Results.vue
src/pages/search/components/result.vue

Generic Contribution not showing up in search (#1513)
search shows wrong titles (#1516)
Comments on wrong proposal (#1515)
- Fixed salary tag for proposal item in search results list
- Fixed wrong titles for search items
As for tasks #1515 and #1516, I was not able to catch this bug, I tried various scenarios and everything works correctly, perhaps the problem is somehow related to caching and we can close them.

fix: fix bugs in search items

---

src/pages/dho/Members.vue
src/pages/proposals/ProposalList.vue

Copy invite link should be main CTA #1522
- Fixed color for CTA buttons on "Members" and "Proposals" pages

fix: fixed color for CTA buttons (#1522)

---

CHANGELOG.md
package.json

This PR fixes updates version number on package.json, and changelog files for the 2.10.1 release

chore(package.json, changelog): update version number and release notes

---

src/components/organization/payouts-widget.vue
src/components/organization/role-assignments-widget.vue
src/pages/dho/Home.vue
src/pages/dho/Organization.vue
src/pages/search/Results.vue

Organization Page: Link to all role assignments shows all contributions #1550
- Fixed widgets links in home and organisation pages

fix: fixed widgets links in home and organisation pages (#1550)

---

src/components/proposals/proposal-view.vue

fix: showing dynamic deferred only on active or archived proposals

---

src/components/proposals/comment-item.vue
src/components/proposals/comments-widget.vue
src/components/proposals/proposal-card.vue
src/components/proposals/proposal-list.vue
src/pages/proposals/ProposalDetail.vue
src/pages/proposals/ProposalList.vue
src/query/proposals/dao-proposal-comment.gql
src/query/proposals/dao-proposal-detail.gql
src/query/proposals/dao-proposals-active-vote.gql
src/query/proposals/dao-proposals-stage.gql

add delete button to comments #1543 
- "Delete" button to proposal comments has been added.
close #1543

feat: add delete button to comments (#1543)

---

src/components/login/register-user-view.vue
src/components/profiles/contact-info.vue
src/mixins/validation.js
src/pages/profiles/profile-creation.vue
src/store/accounts/actions.js
src/store/dao/actions.js

This PR renames validators to better reflect their usage

refactor(validation): rename validators

---

src/layouts/MultiDhoLayout.vue
src/layouts/ProposalLayout.vue

remove padding from dashboard top #1524
- Padding top for dashboard pages has been removed
close #1524

fix: padding top for dashboard pages has been removed (#1524)

---

src/components/dao/settings-design.vue
src/pages/dho/Configuration.vue
src/pages/dho/Explore.vue
src/query/dao-active.gql
src/store/dao/mutations.js

This PR add ability to change banner on the explore page for the Hypha members only.
closes https://github.com/hypha-dao/dho-web-client/issues/1558

feat(configuration): add dynamic explore banner

---

src/components/dao/settings-general.vue
src/pages/dho/Configuration.vue

This PR adds router redirect when url param change
closes https://github.com/hypha-dao/dho-web-client/issues/1614

feat(configuration page): change router url on url change

---

.github/workflows/chromatic.yml
src/components/dao/settings-general.vue
src/components/ipfs/input-file-ipfs.vue
src/layouts/MultiDhoLayout.vue
src/pages/dho/Configuration.vue
src/pages/proposals/create/StepDescription.vue
src/store/dao/mutations.js

chore: stage 2.14.0 

---

src/pages/dho/Configuration.vue

This PR add ability to navigate to certain tab inside Configuration page via query param.

feat(configuration page): add ability to navigate to tab via query

---

.github/workflows/deploy-prod.yml
.github/workflows/deploy-staging.yml
package.json
quasar.conf.js
src/boot/sentry.js
yarn.lock

This PR adds sentry into project so that we can easily track errors in production.
closes https://github.com/hypha-dao/dho-web-client/issues/1665

chore(sentry): init sentry

---

src/components/navigation/bottom-navigation.vue
src/components/profiles/contact-info.vue
src/pages/search/Results.vue

- Fixed a couple of minor visual bugs on mobile

fix(mobile): search columns

---

src/components/common/button-radio.vue

This PR add even padding for the button radio

refactor(button-radio): add even padding

---

quasar.conf.js
src/boot/config.js
src/store/dao/actions.js
src/store/profiles/actions.js

This PR adds HYPHA_CONTRACT to the build env

build(env): add HYPHA_CONTRACT to build env

---

src/layouts/MultiDhoLayout.vue
src/pages/dho/Home.vue
src/store/dao/getters.js

This PR moves all plan vars to the store

refactor(dao store): move expire vars to getters

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml
.github/workflows/deploy-staging.yml

This PR fixes contract name inside github workflow

build(github): fix contract name

---

src/layouts/DhoSelector.vue

This PR fixes race condition that prevents colors to be setup correctly

fix(dho selector): set theme after switching dao

---

src/components/profiles/voting-history.vue

Restored fix that was override on previous merge

fix(mobile): voting history alignment

---

src/layouts/MultiDhoLayout.vue
src/store/dao/actions.js

This PR adds downgrade to free plan flow for plan manager

feat(plan manager): add downgrade plan flow

---

src/components/profiles/members-list.vue
src/components/profiles/profile-card.vue
src/pages/dho/Members.vue
src/pages/profiles/Profile.vue

This PR fixes padding problem on the members page
closes https://github.com/hypha-dao/dho-web-client/issues/1696
Before
After

fix(profile card): add even padding on members page

---

src/components/profiles/profile-card.vue

This PR fixes double props on widget editable

fix(profile card): remove double props on widget-editable

---

src/layouts/DhoSelector.vue

fix: remove console.log

---

src/components/navigation/top-navigation.vue
src/layouts/MultiDhoLayout.vue
src/pages/dho/Home.vue
src/store/dao/mutations.js

This PR hides plan manager components if plan is not activated

feat(plan manager): hide manager if plan not activated

---

src/components/navigation/dho-card.vue
src/components/profiles/profile-card.vue
src/pages/dho/Explore.vue

This PR cleans up explore page layout
closes https://github.com/hypha-dao/dho-web-client/issues/1644

refactor(explore page): clean up

---

cypress/support/e2e.js
src/components/dao/settings-communication.vue
src/components/filters/filter-widget.vue
src/components/form/custom-period-input.vue
src/components/form/text-input-toggle.vue
src/components/navigation/dho-card.vue
src/components/navigation/top-navigation.vue
src/components/profiles/contact-info.vue
src/components/profiles/members-list.vue
src/components/profiles/profile-card.vue
src/components/profiles/wallet-adresses.vue
src/components/profiles/wallet-base.vue
src/css/app.styl
src/layouts/DhoSelector.vue
src/layouts/MultiDhoLayout.vue
src/pages/dho/Explore.vue
src/pages/dho/Home.vue
src/pages/dho/Members.vue
src/pages/dho/Plan.vue
src/pages/profiles/profile-creation.vue
src/pages/proposals/create/OptionsArchetypes.vue
src/pages/proposals/create/OptionsBadges.vue
src/pages/proposals/create/StepCompensation.vue
src/pages/proposals/create/StepDescription.vue
src/pages/proposals/create/StepIcon.vue
src/query/dao-active.gql
src/query/main-dho.gql
src/store/dao/getters.js
src/store/dao/mutations.js
src/store/dao/state.js

chore: stage 2.15

---

src/components/profiles/wallet-base.vue

Profile Page - Wallet link #1647
- fixed wallet link in profile page
close #1647

fix: fixed wallet link in profile page (#1647)

---

src/components/navigation/dho-card.vue
src/css/quasar-classes-override.styl
src/pages/dho/Explore.vue

This PR fixes visual bugs related to explore page

fix(dho card): add fixed height card sections

---

src/components/common/base-banner.vue
src/pages/dho/Home.vue
src/pages/dho/Members.vue
src/pages/dho/Organization.vue
src/pages/proposals/ProposalList.vue

This PR adds split prop to the base banner so that it has display contant in split view

feat(base banner): add split prop

---

src/pages/dho/Plan.vue

This PR add sort to the plans and offers so that it goes from minimum to maximum

feat(plan page): sort plans and offers

---

src/components/login/register-user-view.vue

This PR fixes wrong indentation  that is preventing register screen to works correctly
https://discord.com/channels/722537361480613950/732285564384051323/1033057308747509821

fix(register): add correct indentation

---

src/pages/proposals/ProposalList.vue

Proposal Page: Learn more button not linking #1645
- fixed "Learn more" button for proposal list banner
close #1645

fix: fixed "Learn more" button for proposal list banner (#1645)

---

src/components/profiles/profile-card.vue

This PR fixes profile card where username was shown instead of full name
Before
After

fix(profile card): display correct data

---

cypress/support/e2e.js
src/components/common/base-banner.vue
src/components/common/widget.vue
src/components/login/register-user-view.vue
src/components/navigation/dho-card.vue
src/components/navigation/profile-sidebar-guest.vue
src/components/organization/treasury-widget.vue
src/components/profiles/active-assignments.vue
src/components/profiles/organizations.vue
src/components/profiles/profile-card.vue
src/components/profiles/wallet-base.vue
src/components/proposals/creation-stepper.vue
src/components/proposals/proposal-list.vue
src/css/quasar-classes-override.styl
src/layouts/DhoSelector.vue
src/layouts/LoginLayout.vue
src/layouts/MultiDhoLayout.vue
src/pages/dho/Explore.vue
src/pages/dho/Home.vue
src/pages/dho/Members.vue
src/pages/dho/Organization.vue
src/pages/dho/Plan.vue
src/pages/onboarding/NLogin.vue
src/pages/profiles/Profile.vue
src/pages/proposals/ProposalList.vue
src/pages/proposals/create/OptionsArchetypes.vue
src/pages/proposals/create/OptionsBadges.vue
src/pages/proposals/create/StepProposalType.vue
src/store/dao/getters.js

chore: stage 2.16.0

---

src/components/organization/archetypes-widget.vue
src/components/organization/badges-widget.vue
src/components/organization/payouts-widget.vue
src/components/organization/role-assignments-widget.vue
src/pages/dho/Organization.vue

- Added isMobile prop to widgets, this changes the position of the more button to the bottom,

feat(mobile): add widget bottom more button (#1756)

---

src/components/login/register-user-view.vue
src/components/profiles/contact-info.vue
src/components/profiles/profile-picture.vue
src/components/profiles/voting-history.vue
src/pages/onboarding/NLogin.vue
src/pages/profiles/Profile.vue

Mobile Bugs #1752
- fixed ui bugs in profile page
- fixed scroll in login pages
- hide scroll bar on login screens for mobile
close #1752

fix(mobile): various UI bugs

---

src/css/app.styl

This PR fixes rounded border class that was creating visual bugs

fix(style): add specificity for rounded border q-input

---

src/mixins/validation.js

This PR adds max and min validators for inputs

feat(validation): add max min validators

---

src/components/common/widget.vue

- added new prop "titleSize" for widget component

feat(widget): add "titleSize" prop

---

src/pages/dho/Treasury.vue

Mobile: Treasury Page #1753
- added mobile design for treasury page
close #1753

feat(treasury page): add mobile design

---

.github/workflows/deploy-prod.yml

This PR changes broken telos endpoint

build(github workflow): change telos endpoint var

---

src/components/navigation/profile-sidebar.vue
src/components/navigation/quick-links.vue
src/layouts/MultiDhoLayout.vue
src/router/routes.js

#1697
- Only authorized users can get into proposal creation

fix(router): allow only authorized users onto proposal creation page

---

src/pages/search/components/result.vue

Organisation Page: see all for generic contributions doesn't show results #1633
Some items were not showing up in search results due to invalid tags. For example, Genetic Contribution does not have a salary attribute.
close #1633

fix(search): some search items were not showing up (#1633)

---

src/components/organization/create-dho-widget.vue
src/layouts/CreateLayout.vue
src/layouts/DhoSelector.vue
src/pages/onboarding/create.vue
src/query/dao-created.gql
src/router/index.js
src/router/routes.js
src/store/dao/actions.js

This PR adds dao launcher feature as part of Milestone 2
closes https://github.com/hypha-dao/dho-web-client/issues/1603
closes https://github.com/hypha-dao/dho-web-client/issues/1709
In order to test append /create to url ex. `http://localhost:8080/hypha/create`
Desktop
Mobile

feat: dao-launcher

---

src/components/proposals/proposal-card.vue
src/query/proposals/dao-proposals-stage.gql
src/utils/proposal-parsing.js

Staging Card: Date missing #1668
- Fixed displaying date for staging proposals
close #1668

fix(proposals): date display for props with staging status (#1668)

---

src/pages/dho/Treasury.vue

Treasury Page Sorting #1773
- Fixed search results sorting in treasury page
close #1773

fix(treasury): sorting search results in treasury page (#1773)

---

src/components/common/base-banner.vue
src/components/profiles/profile-card.vue
src/css/quasar-classes-override.styl

This PR fixes border radius discrepancy on safari
closes https://github.com/hypha-dao/dho-web-client/issues/1690

fix(safari): show correct border radius

---

src/components/profiles/profile-card.vue

This PR fixes time formating for time on the profile card
closes https://github.com/hypha-dao/dho-web-client/issues/1699

fix(profile card): add correct time format

---

src/layouts/MultiDhoLayout.vue
src/pages/dho/Members.vue

This PR fixes issues of Become member not showing for users who are not members and not applicants
closes https://github.com/hypha-dao/dho-web-client/issues/1776

fix(members): show become member if not member and applicant

---

src/layouts/MultiDhoLayout.vue
src/layouts/ProposalLayout.vue

Hide scrollbar #1638 
- Layout scrollbar has been hided
close #1638

fix(design): hide layout scrollbar (#1638)

---

src/pages/proposals/ProposalDetail.vue
src/pages/search/Results.vue

Add loading stage for new pages #1775
- Fixed display loader in some pages
close #1775

fix(design): loaders for some pages (#1775)

---

src/layouts/MultiDhoLayout.vue

Remove padding at the bottom of container #1639
- Fixed vertical paddings for multi dho layout
close #1639

fix(design): multi dho layout paddings (#1639)

---

src/layouts/MultiDhoLayout.vue

fix(multi-dho-layout): change bg color class

---

src/layouts/MultiDhoLayout.vue

chore: stage 2.18.2

---

src/apollo/apollo-client-hooks.js
src/layouts/MultiDhoLayout.vue

chore: release 2.18.2

---

src/components/dashboard/support-widget.vue
src/layouts/MultiDhoLayout.vue
src/pages/dho/Home.vue

Primary Button Styling on hover #1640
- Fixed styling on hover for few buttons
close #1640

fix(design): primary button styling on hover (#1640)

---

src/pages/proposals/ProposalList.vue
src/query/proposals/dao-proposals-active-vote-subs.gql
src/query/proposals/dao-proposals-stage-subs.gql

- Added subscriptions to the proposal list
- UI updates in real-time when voting changes
- UI updates in real-time when staging state changes
- UI updates in real-time proposal is added or deleted

feat(subscriptions): add proposal list subscriptions

---

src/pages/dho/Treasury.vue

#1822 
Fixes the bug of UI representation of payments that have decimal point

fix: pending issue for values with decimal points

---

src/pages/dho/Treasury.vue

chore(stage): 2.18.5

---

src/components/common/button-radio.vue
src/components/organization/treasury-token.vue
src/components/plan/chip-plan.vue
src/css/quasar-classes-override.styl
src/layouts/MultiDhoLayout.vue
src/pages/dho/Plan.vue
src/store/dao/getters.js

Fixes the style errors and bugs on the following tickets: 
#1847 
#1843 
Testing: 
Plan manager is on http://localhost:8080/hypha/plan

fix(plan manager): style and bug fixes

---

src/pages/proposals/create/StepDateDuration.vue

without issue
Fixed the maximum number of periods when choosing a date

fix(proposals): maximum periods in choose date step

---

package.json
src/components/common/button-radio.vue
src/components/dashboard/support-widget.vue
src/components/navigation/dho-card.vue
src/components/organization/treasury-token.vue
src/components/plan/chip-plan.vue
src/components/profiles/about.vue
src/components/profiles/members-list.vue
src/css/quasar-classes-override.styl
src/graphql/subscription/dao-active.subscription.gql
src/layouts/MultiDhoLayout.vue
src/pages/dho/Plan.vue
src/pages/profiles/profile-creation.vue
src/pages/proposals/ProposalDetail.vue
src/pages/proposals/ProposalList.vue
src/pages/proposals/create/StepDateDuration.vue
src/pages/proposals/create/StepDescription.vue
src/query/dao-active.gql
src/query/dao-created.gql
src/query/proposals/dao-proposals-active-vote-subs.gql
src/query/proposals/dao-proposals-active-vote.gql
src/store/dao/getters.js
src/store/dao/mutations.js

chore: stage 2.19.0

---

src/components/proposals/proposal-card-chips.vue
src/components/proposals/proposal-card.vue

New Design Staging Card #1764
- Integrated new design for staging card
close #1764

feat(design): integrated new design for staging card (#1764)

---

package.json
src/components/proposals/proposal-card-chips.vue
src/components/proposals/proposal-view.vue
src/pages/proposals/ProposalDetail.vue
src/query/proposals/dao-proposal-detail.gql

Badge Detail Page New Design #1841
- Added new design for Badge detail page
@leonieherma1, I have integrated the new design, but have not yet created new DAO Functions and Purpose fields, as there is no data for this, but this can be added as one field in the description when creating the proposal and edited in bold. Once Gerry creates the individual fields, I'll make a quick fix and add them as part of another issue.
close #1841

feat(design): badge detail page new design (#1841)

---

src/components/organization-asset/asset-card.vue
src/components/organization-asset/asset-list.vue
src/components/organization-asset/create-badge-widget.stories.js
src/components/organization-asset/create-badge-widget.vue
src/components/profiles/profile-picture.vue
src/pages/dho/OrganizationalAssets.vue
src/router/routes.js

Badge Page New Design #1840
- Integrate new design for badge page
close #1840

feat(design): badge page new design (#1840)

---

src/pages/proposals/create/StepDescription.vue
src/utils/proposal-parsing.js

Titles are duplicated when extending role assignments #1735
- Fixed duplicate titles in proposal with edit type
close #1735

fix(step-description): duplicated titles in proposal with edit type (#1735)

---

src/components/proposals/proposal-card.vue
src/components/proposals/proposal-list.vue
src/pages/proposals/ProposalDetail.vue
src/pages/proposals/ProposalList.vue

Empty state filters proposal page #1893 
- Added empty state filters in proposal page
close #1893

fix(proposal-list): added empty state filters in proposal page (#1893)

---

src/components/plan/downgrade-pop-up.stories.js
src/components/plan/downgrade-pop-up.vue
src/pages/dho/Plan.vue

without issue
- Created downgrade pop-up

feat(plan-manager): added downgrade pop-up

---

src/pages/proposals/ProposalDetail.vue

Little fix in Proposal Detail component

fix(ProposalDetail): typo fix

---

src/layouts/MultiDhoLayout.vue

Change route from plan-manager to configuration

fix(expired plan banner): change allowed route names

---

src/pages/proposals/ProposalCreate.vue
src/store/proposals/index.js

Draft issues #1909
- Fixed bug when user trying continue draft proposal
close #1909

fix(draft): bug when user trying continue draft proposal (#1909)

---

src/pages/proposals/ProposalList.vue

without issue
- Fixed condition variable for display "Create new proposal" widget

fix(proposal-list): added missing condition variable

---

src/components/proposals/creation-stepper.vue
src/pages/onboarding/create.vue
src/pages/proposals/ProposalCreate.vue
src/pages/proposals/create/StepCompensation.vue
src/pages/proposals/create/StepDateDuration.vue
src/pages/proposals/create/StepDescription.vue
src/pages/proposals/create/StepIcon.vue
src/pages/proposals/create/StepProposalType.vue
src/pages/proposals/create/StepReview.vue

Sliding Design Feedback #1906
Fixed the following issues:
- When you select a proposal type, no need to have the button “next”. User could directly go/slide to next step
- Auto Slide: sometimes doesnt work, and user get stuck at the “current” step
- Next button: sometimes doesn't trigger the animation/auto slide to the next step
- Small redesign mobile version
close #1906

fix(sliding-design): issues after feedback (#1906)

---

src/components/dao/settings-plan.vue
src/components/plan/billing-history-card.stories.js
src/components/plan/billing-history-card.vue
src/query/_pages/plan-page-query.gql

Added plan manager billing history components #1845

feat(plan): add billing history

---

src/components/proposals/proposal-view.vue
src/pages/proposals/ProposalCreate.vue
src/pages/proposals/ProposalDetail.vue
src/pages/proposals/create/StepDescription.vue
src/pages/proposals/create/StepIcon.vue
src/pages/proposals/create/StepReview.vue
src/pages/proposals/create/config.json
src/query/proposals/dao-proposal-detail.gql
src/store/proposals/index.js
src/utils/proposal-parsing.js

Proposal Creation Wizard: Badge Type #1849
- Improved badge type creation flow
close #1849

feat(badge-type): creation badge type page (#1849)

---

src/pages/onboarding/create.vue
src/pages/proposals/ProposalCreate.vue

Proposal Creation: center each step to the middle of the screen #1918
- Fixed centering widgets in sliding design
close #1918

fix(sliding-design): centering widgets (#1918)

---

src/pages/proposals/ProposalCreate.vue

Edit staged proposal bug #1928
- Fixed bug with editing created proposals
close #1928

fix(proposal-create): not possible to edit previously created proposals (#1928)

---

src/pages/proposals/ProposalDetail.vue

Without issue
- Fixed bug with displaying badge holders widget

fix(proposal-details): bug with displaying badge holders widget

---

src/components/profiles/active-assignments.vue
src/pages/profiles/Profile.vue

Fixes visual bugs related to ipad responsive design
closes https://github.com/hypha-dao/dho-web-client/issues/1783

fix(mobile): add ipad style fixes

---

src/components/common/button-radio.vue

This PR fixes visual bug wtih button card aligment
closes https://github.com/hypha-dao/dho-web-client/issues/1790

fix(button card): align text with check icon

---

src/components/profiles/proposal-item.vue
src/pages/proposals/ProposalCreate.vue
src/pages/proposals/create/StepDateDuration.vue
src/pages/proposals/create/config.json

This Pr fixes proposal extension
closes https://github.com/hypha-dao/dho-web-client/issues/1923
@pmmm When you are testing you need to create new proposal make it pass, wait for it to end and then click extend assignment. Its tricky to test, i dont know if @Gerard097 has some suggestion how can we speed up?

fix(proposal extenstion): enable proposal extension

---

src/components/proposals/proposal-card-chips.vue
src/components/proposals/proposal-view.vue
src/pages/proposals/create/StepDescription.vue
src/pages/proposals/create/config.json

Proposal Creation Wizard: Badge Assignment #1851
- Proposal Creation Wizard: Badge Assignment design has been improved
close #1851

feat(badge-assignment): improvements design for proposal creation with badge assignment type (#1851)

---

src/pages/dho/Explore.vue
src/pages/dho/Members.vue
src/pages/dho/Treasury.vue
src/pages/proposals/ProposalList.vue

Change filters #1804
- Filters has been improved
close #1804

fix(filters): some improvements in filter-widget (#1804)

---

src/pages/proposals/ProposalCreate.vue

Proposals (draft): fix not scrolling to the end #1924
- Fixed scrolling to the end in continue draft proposal
close #1924

fix(draft): bug when continue draft proposal not scrolling to the end (#1924)

---

src/components/profiles/wallet-base.vue
yarn.lock

#1813
The wallet base component was missing the calls to showNotification after an error occurred, I added them so now after an error the notification will be correctly shown

fix: add wallet error notifications

---

src/components/organization-asset/asset-card.vue
src/components/organization-asset/create-badge-widget.vue
src/components/profiles/profile-picture.vue
src/components/proposals/icon-card.vue
src/pages/proposals/ProposalCreate.vue
src/pages/proposals/ProposalDetail.vue
src/pages/proposals/create/OptionsArchetypes.vue
src/pages/proposals/create/OptionsBadges.vue

without issue
- Fixed apply button transition logic
- Replaced q.platform to q.screen

fix: badges improvements

---

src/components/dao/settings-plan.vue

This PR fixes problem with showing  error message even thought user has enough amount of tokens, and also it fixes logic for detecing if user is downgrading plan

fix(plan manager): show correct amount of tokens

---

src/components/dashboard/support-widget.vue
src/graphql/subscription/dao-active.subscription.gql
src/pages/dho/Home.vue
src/query/dao-active.gql
src/query/dao-created.gql
src/store/dao/mutations.js

feat: remove social button when no link

---

src/components/proposals/proposal-card-chips.vue
src/components/proposals/proposal-card.vue
src/components/proposals/proposal-view.vue
src/pages/search/Results.vue
src/pages/search/components/result.vue
src/query/proposals/dao-proposal-detail.gql
src/query/proposals/dao-proposals-active-vote-subs.gql
src/query/proposals/dao-proposals-active-vote.gql
src/query/proposals/dao-proposals-stage-subs.gql
src/query/proposals/dao-proposals-stage.gql

Extension card not showing Proposal Type #1892
- Fixed showing proposal type in proposal card
- Fixed showing proposal type in proposal detail page
- Fixed showing proposal type in search result item
- Fixed bug searching items with extension type
close #1892

fix(proposal): extension card not showing proposal type (#1892)

---

src/components/common/widget-editable.vue
src/pages/profiles/Profile.vue

This PR adds better error message when users saves profile data

feat(profile): add better error message for save profile

---

src/components/dao/settings-general.vue
src/components/dashboard/support-widget.vue
src/pages/dho/Configuration.vue
src/pages/dho/Home.vue
src/query/dao-active.gql
src/store/dao/mutations.js

feat: add documentation settings

---

src/components/dao/settings-plan.vue

This PR rounds plan manager prices by ceiling

feat(plan manager): ceil prices in hypha

---

src/components/login/register-user-view.vue
src/components/login/welcome-view.vue
src/pages/onboarding/NLogin.vue

This PR adds a different copy when we create daos, it's a workaround while we wait for backend changes so https://github.com/hypha-dao/dho-web-client/issues/1794 can be merged
closes https://github.com/hypha-dao/dho-web-client/issues/1976

feat(register): add diffrent copy for onboarding

---

src/components/dao/settings-communication.vue
src/components/dao/settings-design.vue
src/components/dao/settings-general.vue
src/components/dao/settings-plan.vue
src/components/dao/settings-voting.vue

This PR adds correct styling for configuration subtitle

feat(configuration): add correct style for subtitle

---

src/pages/proposals/ProposalCreate.vue
src/pages/proposals/ProposalDetail.vue

Proposal Creation: Fix draft editing #1989
- Fixed title when draft editing
- Fixed first step when draft editing
close #1989

fix(proposal-create): draft editing (#1989)

---

src/pages/dho/MultiSig.vue

#1683 
@arsenijesavic I had to make two separated templated for desktop and mobile because they are too different, we would need to standardize the designs to we can have only one template with flex grids.

feat(mobile): add multi sig styles

---

src/components/proposals/voting.vue
src/pages/proposals/ProposalDetail.vue

This PR removes ability to edit published proposals

fix(proposal): remove edit button

---

src/components/login/login-view.vue

This PR adds correct redirect when user is trying to launch new dao

feat(login-view): add redirect when login via onboard

---

src/css/quasar-classes-override.styl
src/pages/proposals/create/StepDateDuration.vue

This PR adds default look of the calendar after review with @luigicarlini1988

refactor(calendar): return to quesar calendar

---

src/css/app.styl
src/css/components.styl

This PR adds the component module to the global style so that we can have a separate file for creating style components

feat(app-styl): add components module

---

src/components/proposals/comment-item.vue

Proposal Details: Fix comment time since formating #1998
- Fixed a bug when the date of editing a comment when changing when it indicated "1 year ago" although editing could have been made several months ago 
close #1998

fix(comment-item): comment time since formating has been fixed (#1998)

---

src/pages/proposals/ProposalDetail.vue
src/query/proposals/dao-proposal-detail.gql

Proposals: Fix url preview #1999
- Fixed url preview for proposal details
close #1999

fix(proposal-detail): url preview (#1999)

---

src/components/organization-asset/asset-card.vue
src/components/profiles/profile-picture.vue

Badge Card: update layout #1981
- Badge card layout has been updated
close #1981

feat(badges): update card layout (#1981)

---

src/components/organization-asset/asset-card.vue
src/pages/dho/OrganizationalAssets.vue
src/pages/proposals/ProposalDetail.vue
src/query/badges/dao-badges.gql
src/query/proposals/dao-proposal-detail.gql

Badges: Filter badge holders by DAO #2010
- Badge holders filter has been fixed
close #2010

fix(badges): filter badge holders by dao (#2010)

---

src/pages/proposals/ProposalDetail.vue

Proposal Detail: Vote now button not visible (mobile) #2019
- Fixed displaying vote button in proposal details for mobile design
close #2019

fix(voting): vote button not visible in mobile design (#2019)

---

src/components/organization-asset/asset-card.vue
src/pages/upvote-election/UpvoteElection.vue
src/query/upvote-election-data.gql
src/store/proposals/index.js

This PR adds apply action direclty

feat(upvote): add badge apply action

---

src/store/proposals/index.js

This PR adds conditional checks for proposal title

fix(create proposal): add conditional check

---

src/store/proposals/index.js

This PR publises every PR on proposal

feat:  publish every proposal on stage

---

src/store/proposals/index.js

This is hotfix that solves problems with not being able to create proposals due to `details_title_s`
closes https://github.com/hypha-dao/dho-web-client/issues/2064

fix(proposals): add conditional check for draft badge title

---

src/components/dao/settings-community.vue
src/pages/dho/Configuration.vue
src/pages/dho/OrganizationalAssets.vue
src/store/dao/actions.js

This PR adds import election feature to the configuration settings

feat(settings-comminuty): add import election

---

src/pages/dho/Home.vue

This PR add conditional vars to each var in home page so it does not break the production

fix(home): add conditional vars

---

src/store/dao/actions.js

This PR fixes the problem of admins not being able to save configuration settings.

fix(configuration): add check if upvote election id exist

---

src/pages/proposals/create/StepDetails.vue
src/query/circles/dao-circle-list.gql

This PR fixes issue of not getting all circles but just top level

feat(circles): swap getDao with queryCircle

---

src/pages/proposals/create/config.json

This PR changes copy top the proposal creation

refactor(proposal): change budget copy

---

package.json
src/pages/Error404DHO.vue

- Added description for maintenance status in 404 Error page

fix: description for maintenance status

---

src/store/dao/mutations.js

This PR fixes issue that create new proposal is disable
| --- | --- |

fix(configuration): add check if multisig exist

---

package.json
yarn.lock

fixes logout bug with hypha wallet
Logout with hypha wallet was failing because it was storing credentials in a variable that wasn't reset on logout.
1.0.9 of ual-hypha fixes this.

fix: update ual hypha to 1.0.9

---

src/components/profiles/proposal-item.vue

This PR removes unused getters from proposal-item

refactor(proposal-item): remove unused getters

---

src/pages/proposals/create/config.js

This PR add proposal creation config for beta relase

refactor(proposal-create-config): add beta config

---

src/query/circles/dao-circle-list.gql
src/query/circles/dao-circles.gql

This PR updates circle query to fetch only auto approved circles

fix(circle-query): query only auto approved circles

---

src/pages/proposals/create/StepProposalType.vue

This PR fixes issue of autoscrolling when proposal has submenu

fix(step-proposal-type): add auto scroll for submenus

---

src/pages/proposals/ProposalDetail.vue

This PR adds a subscription to the proposal detail query for the smooth UX

feat(proposal-detail): add subscription to the query

---

src/components/dao/widget-circles.vue

This PR fixes the issue of not being able to create circle to the typo bug

fix(widget-circle): add correct variable name

---

src/pages/proposals/create/StepPayout.vue

This PR swaps string values with const

refactor(step-payout): swap string with const

---

src/store/treasury/actions.js

This PR fixes the issue of getSupply creating errors due to the seeds contract

fix(tresury-action): remove seeds call from getSupply

---

src/components/proposals/voter-list.vue

This PR fixes the issue of vote loading from second page

fix(voter-list): add correct index for pagination

---

src/components/profiles/wallet.vue
src/layouts/DhoSelector.vue
src/pages/proposals/ProposalHistory.vue
src/pages/proposals/ProposalList.vue

This PR moves get supply call to the top of the app and removes race condition bugs

refactor(get-supply): move function call to the dho-selector

---

src/pages/proposals/ProposalHistory.vue
src/query/proposals/dao-proposals-history.gql

This PR fixes the issue of autoApproved proposal appearing on the history page

fix(proposal-history): remove autoApproved proposals

---

src/components/proposals/voter-list.vue
src/pages/proposals/ProposalDetail.vue
src/pages/proposals/ProposalList.vue

This PR add fetch policy that is prevent some queries to load properly

fix(proposal): add no cache fetch policy

---

src/components/proposals/voter-list.vue
src/utils/paginate.js

This PR adds separate paginate function and solves issue with last page not showing

fix(voter-list): add paginate function

---

src/components/profiles/wallet.vue
src/components/proposals/voter-list.vue
src/layouts/DhoSelector.vue
src/pages/proposals/ProposalHistory.vue
src/pages/proposals/ProposalList.vue
src/query/proposals/dao-proposals-history.gql
src/utils/paginate.js

- [refactor(get-supply): move function call to the dho-selector (](https://github.com/hypha-dao/dho-web-client/commit/a72f930679fcdfbea3ae6e4d8a3bae7fa22e92f1)
- [fix(proposal-history): remove autoApproved proposals (](https://github.com/hypha-dao/dho-web-client/commit/a4fbd5e30182867365f6e864a8ff9b017f297288)
- [fix(voter-list): add paginate function (](https://github.com/hypha-dao/dho-web-client/commit/cfea6603263982f0d44e64858832d3af75f331a8)

chore: sync develop and master

---

src/layouts/MultiDhoLayout.vue

This PR removes saving notifications to the local storage, and also bug that was blocking the main navigation

refactor(multi-dho-layout): remove local storage notifications

---

src/components/profiles/members-list.vue
src/locales/en.json
src/locales/es.json
src/locales/ko.json
src/locales/pt.json
src/locales/sr.json
src/locales/zh.json
src/pages/dho/Members.vue

This PR refactor member page and fixes issue with pagination

refactor(members): clean up

---

src/layouts/MultiDhoLayout.vue

This PR removes id from notification query

fix(multi-dho-layout): remove ids from query

---

src/pages/proposals/ProposalDetail.vue
src/utils/ipfsy.js

refactor: remove console

---

src/layouts/MultiDhoLayout.vue

fix(multi-dho-layout): add correct var name

---

src/components/dao/widget-roles.vue

This PR add pollInterval in case subscription  is not working
| --- | --- |

fix(widget-roles): add pollInterval

---

src/components/login/register-user-with-captcha-view.vue

This PR fixes the issue when user is logged

fix(onboarding): switch to correct step if isAuthenticated

---

src/pages/proposals/create/StepDuration.vue
src/query/periods-upcoming.gql

This PR adds new query in order to query periods correctly

fix(step-duration): add new periods query

---

src/components/dao/settings-tokens.vue
src/components/dao/settings-voting.vue
src/components/form/custom-period-input.vue
src/components/form/input-slider.vue
src/data/currency.json
src/layouts/DhoSelector.vue
src/locales/en.json
src/pages/dho/Configuration.vue
src/store/dao/actions.js
src/store/dao/getters.js
src/utils/map.js

This PR adds token settings inside the configuration page

feat(configuration): add token settings

---

src/components/dao/settings-general.vue
src/components/dao/settings-voting.vue

This PR adds admin token to the locale

fix(settings): add only admin local string

---

src/const.js
src/pages/proposals/create/StepPayout.vue
src/pages/proposals/create/config.js
src/store/proposals/index.js

This PR adds the ability to input a custom salary when the tier is default ('Custom Tier')

feat(step-payout): add custom input for default tier

---

src/components/filters/filter-widget-mobile.vue
src/components/filters/filter-widget.vue
src/components/navigation/top-navigation.vue
src/layouts/MultiDhoLayout.vue
src/locales/en.json
src/pages/dho/Explore.vue

https://linear.app/hypha/issue/DEV-924/fix-mobile-bugs
- Fixed mobile UI bugs
fixed DEV-924

fix(ui): mobile ui bugs (#DEV-924)

---

src/components/common/payout-amounts.vue
src/pages/proposals/create/StepPayout.vue

fix(settings-token): hide token fields if they not configured

---

src/components/dao/settings-plans-billing.vue
src/components/dao/settings-tokens.vue
src/components/dao/widget-circles.vue

This PR adds guard to all settings that were not disabled when user is not admin

feat(configuration): disable inputs if not admin

---

src/pages/dho/Explore.vue

This PR add sorting daos by created date desc

feat(explore): sort by created date desc

---

src/layouts/MultiDhoLayout.vue

fix(layout): router view displaying bug

---

src/components/login/register-user-with-captcha-view.vue

- Fixed mobile styles in last onboarding step

fix(onboarding): mobile styles last onboarding step

---

src/pages/proposals/create/StepDetails.vue
src/pages/proposals/create/StepPayout.vue

- Fixed proposal creation in mobile version

fix(proposal-creation): creation proposal in mobile version

---

src/pages/dho/Ecosystem.vue
src/pages/dho/Explore.vue

- Fixed mobile filter in Explore DAO page

fix(explore): mobile filter in explore page

---

src/const.js
src/layouts/MultiDhoLayout.vue
src/pages/onboarding/NLogin.vue

- Fixed onboarding screen in mobile version

fix(onboarding): mobile onboarding screen ui

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy-eos-dev.yml
.github/workflows/deploy-eos-prod.yml
.github/workflows/deploy-prod.yml
.github/workflows/deploy-staging.yml
.github/workflows/deploy.branch.yml
quasar.conf.js
src/components/login/register-user-with-captcha-view.vue
src/locales/en.json

- Added download wallet link for mobile version

fix(onboarding): added download wallet link for mobile version

---

src/components/navigation/top-navigation.vue

fix(top-navigation): expand dho button

---

src/pages/dho/Explore.vue

This PR fixes the issue with pagination after search

fix(explore): reset pagination on text filter change

---

src/components/dao/settings-plans-billing.vue
src/const.js
src/store/dao/getters.js

This PR fixes the issue with stripe

fix(settings-plans-billing): add correct values

---

src/components/dao/settings-tokens.vue
src/pages/proposals/create/StepPayout.vue
src/store/dao/mutations.js

This PR fixes the issue with token calculation

fix(token): add correct calculation

---

src/store/proposals/index.js

This PR fixes the issue of not being able to create quest due to the null values

fix(proposal): remove null values

---

src/pages/dho/Members.vue

This PR fixes the issue with poll and pagination on members page

fix(members): comment out pollInterval

---

src/pages/dho/Explore.vue

This PR fixes the issue with poll and pagination on explore page

fix(explore): comment out pollInterval

---

src/pages/proposals/create/StepDetails.vue

- Fixed next button in mobile proposal creation

fix(step-details): next step button on mobile

---

src/pages/dho/Explore.vue

- Fixed horizontal scroll on explore page

fix(explore): horizontal scroll on explore page

---

src/components/login/login-view.vue
src/components/login/register-user-with-captcha-view.vue
src/components/login/welcome-view.vue
src/components/navigation/profile-sidebar-guest.vue

Fix/onboarding UI changes v2

---

src/router/index.js

fix(router): redirecting

---

src/pages/profiles/Profile.vue

https://linear.app/hypha/issue/DEV-934/fix-quest-completion-not-showing-anywhere
- Fixed showing quest complete proposals
fixed DEV-934

fix(quest-proposal): showing quest complete proposals (#DEV-934)

---

package.json
src/store/accounts/actions.js

- Fix ual-hypha pop-up content

fix(ual-hypha): pop-up content

---

src/components/login/login-view.vue

- Fixed return url after login

fix(login-view): return url

---

src/components/login/register-user-with-captcha-view.vue
src/query/dao-created.gql

This PR fixes the issue that users who created dao is not admin due to the race condition

fix(create-dao): add admin check before redirect

---

src/pages/proposals/create/OptionsArchetypes.vue

this pr fixes the issue of default roles not appearing

fix(options-archetypes): remove auto approve on role query

---

src/router/index.js

- Fixed router bug after login (wrong redirect)

fix(router): login bug

---

src/components/profiles/wallet-base.vue
src/locales/en.json
src/locales/es.json
src/locales/ko.json
src/locales/pt.json
src/locales/sr.json
src/locales/zh.json

fix(wallet-base): redeem token bug

---

src/locales/en.json
src/locales/sr.json

https://linear.app/hypha/issue/DEV-943/miss-spelt-word-picture-on-profile-page
- Fixed translations
fixed DEV-943

fix(translations): improvements (#DEV-943)

---

src/layouts/EmptyLayout.vue

- Fixed col width in empty layout

fix(empty-layout): col width

---

src/pages/proposals/create/StepPayout.vue

- Fixed custom reward in payout proposal
fixed DEV-945

fix(step-payout): hide custom reward when tokens not set up

---

src/components/login/login-view.vue

fix(login-view): return url after login

---

src/components/login/register-user-with-captcha-view.vue
src/locales/en.json

- Added loading modal for dao creating process

feat(onboarding): added loading modal for dao creating process

---

src/components/proposals/proposal-view.vue
src/pages/proposals/create/StepPayout.vue

https://linear.app/hypha/issue/DEV-955/remove-the-slider-on-contribution-with-voice-only
- Hide deffered slider when settings tokens not setup
fixed DEV-955

fix(proposals): hide deffered slider when settings tokens not setup (#DEV-955)

---

src/components/organization-asset/asset-card.vue
src/components/organization-asset/asset-list.vue
src/pages/dho/Home.vue
src/pages/dho/OrganizationalAssets.vue
src/pages/proposals/ProposalDetail.vue

- Remove old elections code (404 error in badge details page)

fix(code): remove old elections code

---

src/components/profiles/profile-card.vue

https://linear.app/hypha/issue/DEV-968/duplicated-voice-word
- Fixed duplicate voice token name in profile-card
fixed DEV-968

fix(profile-card): hide duplicate voice token name (#DEV-968)

---

src/pages/dho/Members.vue

This PR adds ability to create magic wallet link

feat(members): add magic wallet link

---

src/components/profiles/wallet-base.vue
src/store/payments/actions.js

add doc ID to memo for redeeming cash tokens
**Needs to be tested on testnet (telos or EOS)**
The smart contract now requires the dao ID in the memo, like this: "redeem,20" where 20 would be the dao ID.

feat: redeem with dao doc id

---

src/store/dao/actions.js

This PR fixes the issue of not being able to create token

fix(action): add correct value for reward_token_max_supply

---

src/pages/dho/Home.vue

This PR fixes the issue of dao title not being reflected in banner

fix(home): add dao title as title param (#DEV-1326)

---

src/components/login/welcome-view.vue
src/locales/en.json
src/pages/onboarding/NLogin.vue
src/store/accounts/actions.js

Create DAO works now
It has 2 modes
When user isn't logged in, it shows "login with pangea" 
When user is logged in, it shows "Create DAO"
Create DAO flow works. 
OG code is really strange, where components do many unrelated things... so it's quite messy. 

Create DAO is working again

---

.github/workflows/deploy-staging.yml

[workflow run](https://github.com/hypha-dao/dho-web-client/actions/runs/12418281878)

chore: remove duplicate env var

---

.github/workflows/deploy-prod.yml

fix: Update deploy-prod.yml with correct variables
