hypha-dao/dho-web-client

- src/store/assignments/actions.js
- src/store/badges/actions.js
- src/store/payouts/actions.js
Updated propsal related queries to make them more efficient, by eliminating expand all instructions and retrieving only the required data
> Updated propsal related queries to make them more efficient

- src/pages/proposals/ProposalDetail.vue
- src/query/proposals/dao-proposal-detail.gql
- Return null when the proposal doesn't have start period field
> Return null when the proposal doesn't have start period field

- src/components/proposals/voting.vue
- Add the new label when the user didn't vote in some proposal and remove mouse actions #764
> Add a new label when user didn't vote in some proposal

- src/store/dao/getters.js
- Add a new getter on dao store to get the unity and quorum values
> Add voting percentages to fix an error with unity and quorum

- src/pages/proposals/ProposalList.vue
Now in the proposal screen, the "Show staging proposals" toggle doesn't leave a blank space when there is nothing to show
> Blank space removed

- src/components/proposals/proposal-view.vue
In proposal-view component, when displaying a "ROLE ARCHETYPE" card, in the Salary band section, the word "null" is no longer being displayed before the actual salary
> Role Archetype proposal null

- src/pages/proposals/ProposalDetail.vue
The "Publish" button no longer appears when the user is not the creator of the proposal.
> Remove "Publish" widget from Proposal Details

- src/components/ipfs/ipfs-image-viewer.vue
- src/components/navigation/dho-btn.vue
- src/components/navigation/dho-card.vue
- src/components/profiles/organizations.vue
- The left side dao explorer now shows the first two letters of the name instead of just one.
- The organization widget now shows the default logo when there is not an image to load.
> Default logo now shows up correctly

- src/components/proposals/comment-item.vue
- src/pages/proposals/ProposalDetail.vue
Fixed a bug that prevented loading of the details page when there were no comments with reactions on the proposal.
- [x ] Github issue details are up to date for people to QA.
- [x ] I have tested all my changes.
> Fixed proposal detail page when there are no comments with reactions

- src/components/common/input-editor.vue
- src/components/common/input-field.vue
- src/mixins/validation.js
- src/pages/proposals/create/StepDescription.vue
Now when the maximum amount of characters is surpased, the border color changes to red and the error message get displayed correctly.
> fix (proposals): title and description error messages restored

- src/store/dao/mutations.js
Added a flag to enable/disable cash claims from backend
> feat: add cash claims flag

- src/components/profiles/proposal-item.vue
- src/pages/proposals/create/StepDescription.vue
* Title and description error messages restored
Now when the maximum amount of characters is surpased, the border color changes to red and the error message get displayed correctly.
* using rules for error messages
* Removed color override
* Updated description length
* Added missing view proposal button on profile
Co-authored-by: Funkalux <funkalux@gmail.com>
| --- | --- |
> fix: proposal description max length (#1496)

- src/pages/dho/Explore.vue
- src/router/index.js
This PR is supposed to only show the create-dho-widget to the Hypha dao member and it is supposed to redirect all non-Hypha daos from the /:dao/create page
closes https://github.com/hypha-dao/dho-web-client/issues/1493
> feat(explore page): show dao creation wizard to hypha members only

- src/components/proposals/proposal-view.vue
Enable deferred button for archived assignments (#1489)
- [] Enabled deferred button for archived assignments
On the frontend side, one little thing was missing to display a button for archive assignments. I added this, but now I'm getting an error from the backend, I think @Gerard097 should enable this on the backend as well, I've seen a similar task https://github.com/hypha-dao/dao-contracts/issues/298 created for him.
> fix: enable deferred button for archived assignments (#1489)

- src/components/common/token-value.vue
- src/pages/proposals/ProposalDetail.vue
- src/pages/proposals/create/StepReview.vue
- src/pages/proposals/create/config.json
- src/utils/proposal-parsing.js
Hide Badge Multiplier #1476
- Hide "Compensation" step for creating and extension badges
- Temporarily added a key to proposals config file to change multipliers to x1
- Added getter isDefaultBadgeMultiplier to display x1 in all assignments created for badges
Since now the multipliers do not work correctly (users receive the same rewards as x1 multipliers) and confuse users, I temporarily created several variables that change the display of all multipliers to x1, and also, at the request of @leonieherma1, hide one of the steps when expanding and creating a Badge assignment.
> fix: Hide Badge Multiplier (#1476)

- src/pages/proposals/create/StepDescription.vue
remove character max from description (frontend) (#1555)
- Warning about character max from description has been removed (#1555)
Removed the character limit in the description, but at the moment I'm getting an error from the backend. I think this also needs to be fixed.
> fix: remove character max from description (frontend) (#1555)

- src/components/navigation/left-navigation.vue
DAO Switcher: don't show DAO I am currently in #1544
- Current DAO in left menu (dao switcher) has been hidden
Added a check to compare the name of the current DAO with those that are displayed in the list
> fix: current dao in left menu (dao switcher) has been hidden (#1544)

- src/pages/proposals/create/StepDescription.vue
remove character max from description (frontend) #1555
- Character max length in creating description for proposal has been fixed.
> fix: character max length in creating description for proposal has been fixed (#1555)

- src/pages/proposals/ProposalDetail.vue
- src/pages/proposals/ProposalList.vue
This PR is adding pull interval after proposal has been published, so that when you click on the proposals after publishing it shows up as publishing and not as staged.
closes https://github.com/hypha-dao/dho-web-client/issues/1488
> feat(proposals): add pull interval for the published proposals

- src/pages/dho/Explore.vue
- src/pages/dho/Members.vue
- src/pages/proposals/ProposalList.vue
- src/pages/search/Results.vue
filter widget: copy cut off #1523
Search filter "show all" #1556
- Select options in filter widget has been fixed (added "ghost" title before options)
- Added "All" option in search filter
> fix: select options in filter widget has been fixed (#1523, #1556)

- src/components/profiles/members-list.vue
- src/components/profiles/profile-card.vue
- src/components/proposals/proposal-card.vue
- src/pages/dho/Members.vue
filter widget should be the same width on all screens #1542
- Fixed filter widget width on all screens and few style fixes on proposal card 
close #1542
> fix: fixes for some ui bugs

- .github/workflows/deploy-dev.yml
- .github/workflows/deploy-prod.yml
- .github/workflows/deploy-staging.yml
[Infura deprecated public gateway](https://docs.infura.io/infura/networks/ipfs/how-to/access-ipfs-content/public-gateway) so this PR adds new settings for ipfs with dedicated gateway
> chore(github): change ipfs id and gateway

- src/mixins/format.js
- src/store/proposals/index.js
Remove decimals from numbers #1597
Remove decimals from numbers in this pages:
- Proposal detail page (token for Utility, Cash & Voice)
- Proposal creation wizard (token for Utility, Cash & Voice)
- Wallet widget on profile
- Wallet widget on wallet page
close #1597
> fix: remove decimals from numbers (#1597)

- src/store/dao/mutations.js
This PR re enables claiming by reading it from the backend.
> feat(dao): read cash claim enable from backend

- .github/workflows/chromatic.yml
This PR updates node version number inside chromatic github workflow because it was not building.
[sample error](https://github.com/hypha-dao/dho-web-client/actions/runs/3114035261/jobs/5049399406):
`
error ipfs-unixfs@6.0.9: The engine "node" is incompatible with this module. Expected version ">=16.0.0". Got "14.20.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Process completed with exit code 1.
`
> chore(github, chromatic): update node version to 16

- src/layouts/MultiDhoLayout.vue
long titles cut off icons in header #1621 
- Added cut off icons for long titles
- Added tooltip for titles
close #1621
> fix: added cut off icons for long titles (#1621)

- src/pages/dho/Configuration.vue
This PR sends url param only if changed because if not it generates error:
`Error: assertion failure with message: URL is already being used, please use a different one url_hypha hypha`
> fix(configuration page): send url only if changed

- .github/workflows/commitlint.yml
This PR removes triggering commitlint on pull request as it is reductant because it is already trigger on push.
> build(commitlint): remove pull request trigger

- src/pages/dho/Treasury.vue
This PR fixes padding between treasury table and filter so that it follows sizing as remaining UI
closes https://github.com/hypha-dao/dho-web-client/issues/1696
Before
After
> fix(treasury page): add even padding

- src/store/dao/getters.js
This PR enables DAO that are not activated to enrol members
> fix(plan manager): enable enrolment if the plan is not activated

- src/components/proposals/comment-input.vue
- src/components/proposals/comments-widget.vue
Disable comments for non members #1698 
- disabled the ability to leave comments to non-members
close #1698
> fix(comment input): disable commenting for non-members (#1698)

- src/router/index.js
prevent members from going to proposal create page #1697
- fixed requiresAuthMember attribute
Fixed typing error. isMember returns a string, not a boolean. Changed !isMember to isMember === 'false'
close #1697
> fix: small fix in router

- src/components/proposals/proposal-card-chips.vue
Change label to USD equivalent #1745
Change label on proposal card to USDE #1736
- Changed proposal card label from USD to USDE
close #1736
close #1745
> fix(proposal): change label from USD to USDE (#1736, #1745)

- src/components/filters/filter-widget-mobile.vue
- src/components/filters/filter-widget.vue
Mobile Design Feedback #1678
- Added save and reset buttons for mobile filter
Many of the errors in this task were caused by the fact that the browser page was not reloaded after installing the mobile platform in chrome. In fact, there are none.
close #1678
> fix(design): added save and reset buttons for mobile filter (#1678)

- src/components/profiles/wallet-base.vue
Profile Page: Wallet widget adjust margin #1648
- Fixed title margin in wallet widget
close #1648
> fix(design): title margin in wallet widget component (#1648)

- src/layouts/MultiDhoLayout.vue
Support Page: Link Button is not active (blue) when on page #1646
- Fixed active support icon for multi-dho-layout
close #1646
> fix(design): active mode for support icon in multi-dho-layout (#1646)

- .github/workflows/deploy-dev.yml
- .github/workflows/deploy-prod.yml
- .github/workflows/deploy-staging.yml
- package.json
- quasar.conf.js
- src/pages/dho/Plan.vue
- yarn.lock
#1761 
- Encrypts the data needed for passing to Hypha Token Sales page
- Calls the appropriate URL on Hypha Token Sales page
We are encrypting the data in order to prevent users from easily updating the amount / account name / token from URL. 
@arsenijesavic 
This is just example on how to generate the hash for Hypha Token Sales `daoActivation` parameter. Feel free to change this PR as you see it fit.
> feat: encrypt data and call hypha token sales url 

- src/pages/proposals/ProposalDetail.vue
- src/pages/proposals/ProposalList.vue
Badge Assignment vote not showing (Quorum & Unity not updating) #1852
- Fixed bug with updating voting info for Edit type 
fetchPolicy 'cache-and-network' doesn't get voting info for edit type props, and removed caching to get props data, it works
close #1852
> fix(proposals): quorum and unity not updating for Edit type (#1852)

- src/layouts/MultiDhoLayout.vue
make configuration settings clickable #1839
- Fixed bug with configuration settings button
close #1839
> fix(layout): configuration settings button is clickable (#1839)

- package.json
- src/components/organization/payout-card.vue
- src/components/organization/role-assignment-card.vue
Organisation Page: Markdown shows wrong in preview #1631
- Fixed wrong preview in payout and role assignment cards
close #1631
> fix(design): markdown shows wrong in preview (#1631)

- .github/workflows/deploy-dev.yml
Points the dev instance of DHO to TestNet version of Hypha Token Sales Page
> build(env): update hypha token sales url with testnet instance url

- src/layouts/MultiDhoLayout.vue
- src/pages/dho/Configuration.vue
- src/store/dao/actions.js
it adds changes in last feedback regarding plan manager
closes https://github.com/hypha-dao/dho-web-client/issues/1919
closes https://github.com/hypha-dao/dho-web-client/issues/1806
> fix(plan manager): add feedback changes

- src/pages/proposals/create/OptionsArchetypes.vue
- src/pages/proposals/create/OptionsBadges.vue
- src/pages/proposals/create/StepProposalType.vue
This PR adds empty states for recurring activities 
so that DAOs that are newly created and don't have any roles or badges don't get confused
closes https://github.com/hypha-dao/dho-web-client/issues/1927
> feat(proposal create): add empty states for recurring activity

- src/components/profiles/profile-card.vue
Profile: show account name & default timezone #1803
- Fixed bug with displaying account name & default timezone
close #1803
> fix(profile-card): show account name & default timezone (#1803)

- src/components/form/emoji-picker.vue
Comment: emoji button overflows borders #1807
- Added border-radius for hover state
close #1807
> fix(emoji-picker): added border-radius for hover state (#1807)

- src/pages/dho/Home.vue
This PR fixes button linking for plan manager
> fix: add correct href for manage plan button

- src/components/dao/settings-communication.vue
- src/components/dao/settings-design.vue
- src/components/dao/settings-general.vue
- src/components/dao/settings-voting.vue
Replaced lorem ipsum copy on the configuration page  `/hypha/configuration`
#1598
> fix(copy): replace configuration copy

- src/components/profiles/contact-info.vue
- src/pages/profiles/Profile.vue
This PR moves contact widget below profile card so that its clear to the user where to input data due to the error on the backend that requires that users has phone or email in order to add other data
> feat(profile): move contact widget below about

- src/components/dao/settings-plan.vue
This PR fixes the issue of usd to hypha conversion.
The prices are not displayed correctly.
> fix(plan manager): show correct prices

- src/components/proposals/proposal-view.vue
- src/pages/proposals/ProposalDetail.vue
#1961 
Note: I noticed we are manually refetching the queries instead of using the gql subscriptions, I remember I added subscriptions to this page some time ago, did that got removed for some reason?
> fix: remove blink on proposal publish

- src/components/navigation/non-member-menu.vue
After review with @luigicarlini1988 we decided that its redutant to have logout both on top bar and side bar, so this PR removes logout button from the top.
closes https://github.com/hypha-dao/dho-web-client/issues/1970
> refactor(non members menu): remove logout button

- src/components/dao/settings-plan.vue
This PR solves the issue where buttons were not clickable even when user selected plan, period, and have enought tokens.
closes https://github.com/hypha-dao/dho-web-client/issues/1971
> fix(plan manager): enable cta when plan and period selected

- src/components/organization-asset/asset-card.vue
- src/components/organization-asset/asset-list.vue
- src/components/organization-asset/create-badge-widget.vue
This PR fixes grid issue with Badges page, where the page was showing only two column and empty space on the right.
Now there is correct three column grid.
closes https://github.com/hypha-dao/dho-web-client/issues/1974
> fix(badges): add three column grid for asset card

- src/components/proposals/proposal-view.vue
- src/pages/proposals/ProposalDetail.vue
- src/query/proposals/dao-proposal-detail-subs.gql
- src/query/proposals/dao-proposal-detail.gql
- src/utils/proposal-parsing.js
#1596 
- Changed the way the compensation is calculated on proposal detail to be able to display it dynamically while the percentages change. 
- Also did a small refactor to have an optimistic proposal before the DB update happens
> fix: show actual compensation on commitment change

- src/pages/proposals/create/StepDescription.vue
Proposal Creation: Disable next button if not all required are filled #1986
- Fixed disabling next button if not all required are filled
close #1986
> fix(proposal-creation): disable next button if not all required are filled (#1986)

- src/layouts/MultiDhoLayout.vue
- src/pages/dho/Home.vue
This PR adds correct links for manage plan buttons
> fix(plan-manager): add correct linking for manage plan buttons

- src/components/navigation/top-navigation.vue
- src/layouts/MultiDhoLayout.vue
This PR removes the plan manager button from the top navigation since the plan manager is no longer a separate page
> fix(top-navigation): remove plan manager button

- src/pages/proposals/ProposalList.vue
- src/pages/support/Support.vue
This PR adds the ability to read the documentation url from the backend instead of being hardcoded
> fix(documentation-url): add dynamic links

- src/components/common/base-banner.vue
This PR fixes issue with wrong class name for the base banner that was making corner sharp
> fix(style): rename rounded-corners to the rounded-full

- src/pages/dho/Home.vue
- src/pages/dho/Organization.vue
Active Badges are not showing in the DAO page #2018
- Fixed displaying active badges in dao page
close #2018
> fix(badges): displaying active badges in dao page (#2018)

- src/pages/dho/Configuration.vue
- src/query/dao-active.gql
- src/store/dao/actions.js
- src/store/dao/mutations.js
This PR adds createupvelc and editupvelc actions that manage the state of the election
> feat(configuration page): add createupvelc and editupvelc actions

- src/pages/dho/Home.vue
This PR fixes the issue of CSS grid on larger screen not being displayed correctly
> fix(home): add default grid

- src/components/common/widget.vue
This PR fixes CSS grid on the home page
> fix(widget): add min width

- src/components/profiles/profile-picture.vue
This PR removes margin on the profile picture
> refactor(profile-picture): remove margin

- src/components/dao/widget-roles.vue
This PR adds fixes where graphql data has been read from an empty array rather then graphql var
> fix(widget-roles): read graphql data

- src/components/dao/widget-circles.vue
This PR fixes the issue of when creating a new circle, the name of the previous circle appear by default
> fix(widget-circle): minor typo in code

- src/pages/dho/Explore.vue
This PR adds poll interval to the dho query so that daos appear automatically
> feat(explore): add poll interval to dhos query

- src/pages/profiles/Profile.vue
This PR fixes the issue of new profile not loading
> fix(profile): not loading (#DEV-926)

- src/components/navigation/dho-card.vue
This PR fixes the issue of overflowing text
> fix(dho-card): add text truncate for title

- src/components/dao/settings-plans-billing.vue
- src/const.js
- src/layouts/DhoSelector.vue
- src/layouts/MultiDhoLayout.vue
- src/store/dao/getters.js
- src/store/dao/mutations.js
This PR adds full stripe workflow
> feat: stripe

- src/pages/proposals/ProposalDetail.vue
When trying to complete quests with a title longer than 50 characters, the smart-contract rejects the call.
> fix(ProposalDetail): do not append [COMPLETION]
